name: Fetch testnet storage node metrics

on:
  workflow_dispatch:
  schedule:
    - cron:  '37 0/12 * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch and write data
      run: |-
        git pull
        ENDPOINTS_JSON=`curl --max-time 5 --silent https://assets.verida.io/registry/storageNodes/testnet.json`
        ENDPOINTS=`echo $ENDPOINTS_JSON |  jq ".[] .serviceEndpoint"`
        for ENDPOINT in $ENDPOINTS; 
        do
          ENDPOINT=`echo $ENDPOINT | sed -e 's:\"::g'` # remove quotes
          STRIPPED_FINAL_SLASH=`echo $ENDPOINT | sed 's/.$//'` # remove final slash
          echo $STRIPPED_FINAL_SLASH
          JSON=`curl --max-time 5 --silent "$STRIPPED_FINAL_SLASH/status"`
          echo $JSON
          CURRENT_USERS=`echo $JSON | jq .results.currentUsers`
          MAX_USERS=`echo $JSON | jq .results.maxUsers`
        
          DOMAIN_NAME=`echo $ENDPOINT | sed -E -e 's_.*://([^/@]*@)?([^/:]+).*_\2_'` # get the domainname
        
          mkdir -p "./nodes/$DOMAIN_NAME"
        
        
          if [ ! -f "./nodes/$DOMAIN_NAME/stats.csv" ]; then
            # the CSV doesn't exist, so create it and add the header
            echo "datetime_utc,current_users,max_users" > "./nodes/$DOMAIN_NAME/stats.csv"
          fi
        
          # append stats to the CSV
          TZ=UTC printf "%(%F %T)T, %d, %d\n" $EPOCHSECONDS $CURRENT_USERS $MAX_USERS >> ./nodes/$DOMAIN_NAME/stats.csv
        done

        git add .
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: yarn
    - name: Merge Node Stats
      run: |
        yarn install
        yarn build && yarn run process
        git add ../nodes/*.json
      working-directory: ./mergestats
    - name: Commit and push if it changed
      uses: stefanzweifel/git-auto-commit-action@v4
    - name: Upload to S3
      uses: shallwefootball/s3-upload-action@master
      with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'nodes'
          destination_dir: 'metrics/nodes'
    - name: Invalidate Cloudfront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: "E3LHLBYD4D78TS"
        PATHS: '/metrics/nodes/*'
        AWS_REGION: 'us-west-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
