name: Fetch latest testnet DID count

on:
  workflow_dispatch:
  # schedule:
  #   - cron:  '27 */12 * * *'
jobs:
  did-metrics:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch and write data
      run: |-
        git pull
        export ACTIVEDIDS=`curl https://data.verida.network/network/testnet/stats | jq .activeDIDs`
        TZ=UTC printf "%(%F %T)T, %d\n" $EPOCHSECONDS $ACTIVEDIDS >> network/testnet/stats.csv
    - name: Commit and push if it changed
      uses: stefanzweifel/git-auto-commit-action@v4
    - name: Upload to S3
      uses: shallwefootball/s3-upload-action@master
      with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'network/testnet'
          destination_dir: 'metrics/network/testnet'
    - name: Invalidate Cloudfront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: "E3LHLBYD4D78TS"
        PATHS: '/metrics/network/testnet/*'
        AWS_REGION: 'us-west-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
